---
- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - Deploy Swarmpit."
  docker_container:
    name: "{{ swarmpit_stack_name }}"
    image: "{{ swarmpit_image }}:{{ swarmpit_version }}"
    state: "{{ swarmpit_state }}"
    volumes_from:
      - "/var/run/docker.sock:/var/run/docker.sock"
  when:
    - inventory_hostname == docker_swarm_primary_manager_name
